// Fetch all movies/TV series actions
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";
export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_RESET = "MOVIES_LIST_RESET";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";

// Fetch movie detail actions
export const MOVIE_DETAIL_FAIL = "MOVIE_DETAIL_FAIL";
export const MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST";
export const MOVIE_DETAIL_RESET = "MOVIE_DETAIL_RESET";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";

// Fetch TV detail actions
export const TV_DETAIL_FAIL = "TV_DETAIL_FAIL";
export const TV_DETAIL_REQUEST = "TV_DETAIL_REQUEST";
export const TV_DETAIL_RESET = "TV_DETAIL_RESET";
export const TV_DETAIL_SUCCESS = "TV_DETAIL_SUCCESS";

// Fetch landing page trending movies
export const TRENDING_FAIL = "TRENDING_FAIL";
export const TRENDING_REQUEST = "TRENDING_REQUEST";
export const TRENDING_SUCCESS = "TRENDING_SUCCESS";

// Fetch landing page now playing (Movies)
export const LATEST_MOVIE_FAIL = "LATEST_MOVIE_FAIL";
export const LATEST_MOVIE_REQUEST = "LATEST_MOVIE_REQUEST";
export const LATEST_MOVIE_SUCCESS = "LATEST_MOVIE_SUCCESS";

// Fetch landing page on the air (TV)
export const LATEST_TV_FAIL = "LATEST_TV_FAIL";
export const LATEST_TV_REQUEST = "LATEST_TV_REQUEST";
export const LATEST_TV_SUCCESS = "LATEST_TV_SUCCESS";

// Fetch movie recommendation
export const MOVIE_RECOMMENDATION_FAIL = "MOVIE_RECOMMENDATION_FAIL";
export const MOVIE_RECOMMENDATION_REQUEST = "MOVIE_RECOMMENDATION_REQUEST";
export const MOVIE_RECOMMENDATION_RESET = "MOVIE_RECOMMENDATION_RESET";
export const MOVIE_RECOMMENDATION_SUCCESS = "MOVIE_RECOMMENDATION_SUCCESS";

// Fetch TV recommendation
export const TV_RECOMMENDATION_FAIL = "TV_RECOMMENDATION_FAIL";
export const TV_RECOMMENDATION_REQUEST = "TV_RECOMMENDATION_REQUEST";
export const TV_RECOMMENDATION_RESET = "TV_RECOMMENDATION_RESET";
export const TV_RECOMMENDATION_SUCCESS = "TV_RECOMMENDATION_SUCCESS";

//Recommendation Reducer
export const FETCH_MOVIE_RECOMMENDATION = "FETCH_MOVIE_RECOMMENDATION";
export const FETCH_TV_RECOMMENDATION = "FETCH_TV_RECOMMENDATION";
export const START_RECOMMENDATION_LOADING = "START_RECOMMENDATION_LOADING";
export const STOP_RECOMMENDATION_LOADING = "STOP_RECOMMENDATION_LOADING";
export const RECOMMEDNATION_ERROR = "RECOMMEDNATION_ERROR";
