// Fetch all movies/TV series actions
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";
export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_RESET = "MOVIES_LIST_RESET";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";

// Fetch movie detail actions
export const MOVIE_DETAIL_FAIL = "MOVIE_DETAIL_FAIL";
export const MOVIE_DETAIL_REQUEST = "MOVIE_DETAIL_REQUEST";
export const MOVIE_DETAIL_RESET = "MOVIE_DETAIL_RESET";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";

// Fetch TV detail actions
export const TV_DETAIL_FAIL = "TV_DETAIL_FAIL";
export const TV_DETAIL_REQUEST = "TV_DETAIL_REQUEST";
export const TV_DETAIL_RESET = "TV_DETAIL_RESET";
export const TV_DETAIL_SUCCESS = "TV_DETAIL_SUCCESS";

// Fetch landing page trending movies
export const TRENDING_FAIL = "TRENDING_FAIL";
export const TRENDING_REQUEST = "TRENDING_REQUEST";
export const TRENDING_SUCCESS = "TRENDING_SUCCESS";

//Fetch landing page now playing (Movies)
export const NOW_MOVIES_FAIL = "NOW_MOVIES_FAIL";
export const NOW_MOVIES_REQUEST = "NOW_MOVIES_REQUEST";
export const NOW_MOVIES_SUCCESS = "NOW_MOVIES_SUCCESS";

//Fetch landing page on the air (TV)
export const NOW_TV_FAIL = "NOW_TV_FAIL";
export const NOW_TV_REQUEST = "NOW_TV_REQUEST";
export const NOW_TV_SUCCESS = "NOW_TV_SUCCESS";

//Landing Reducer
export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_NOW_MOVIE = "FETCH_NOW_MOVIE";
export const FETCH_NOW_TV = "FETCH_NOW_TV";
export const START_LANDING_LOADING = "START_LANDING_LOADING";
export const STOP_LANDING_LOADING = "STOP_LANDING_LOADING";
export const LANDING_ERROR = "LANDING_ERROR";

//Recommendation Reducer
export const FETCH_MOVIE_RECOMMENDATION = "FETCH_MOVIE_RECOMMENDATION";
export const FETCH_TV_RECOMMENDATION = "FETCH_TV_RECOMMENDATION";
export const START_RECOMMENDATION_LOADING = "START_RECOMMENDATION_LOADING";
export const STOP_RECOMMENDATION_LOADING = "STOP_RECOMMENDATION_LOADING";
export const RECOMMEDNATION_ERROR = "RECOMMEDNATION_ERROR";
