//Movie Reducer
export const SET_NAME = "SET_NAME";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_INFO = "FETCH_MOVIE_INFO";
export const FETCH_TV_INFO = "FETCH_TV_INFO";
export const START_MOVIE_LOADING = "START_MOVIE_LOADING";
export const STOP_MOVIE_LOADING = "STOP_MOVIE_LOADING";
export const MOVIE_ERROR = "MOVIE_ERROR";

//Landing Reducer
export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_NOW_MOVIE = "FETCH_NOW_MOVIE";
export const FETCH_NOW_TV = "FETCH_NOW_TV";
export const START_LANDING_LOADING = "START_LANDING_LOADING";
export const STOP_LANDING_LOADING = "STOP_LANDING_LOADING";
export const LANDING_ERROR = "LANDING_ERROR";

//Recommendation Reducer
export const FETCH_MOVIE_RECOMMENDATION = "FETCH_MOVIE_RECOMMENDATION";
export const FETCH_TV_RECOMMENDATION = "FETCH_TV_RECOMMENDATION";
export const START_RECOMMENDATION_LOADING = "START_RECOMMENDATION_LOADING";
export const STOP_RECOMMENDATION_LOADING = "STOP_RECOMMENDATION_LOADING";
export const RECOMMEDNATION_ERROR = "RECOMMEDNATION_ERROR";
